# Generated by Django 5.0.3 on 2024-03-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='database',
        ),
    ]
